---
- name: Update repositories
  ansible.builtin.apt:
    cache_valid_time: 86400
    update_cache: yes

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - nginx
      - certbot
    state: present
