---
- name: Open tcp 80
  ansible.builtin.iptables:
    action: insert
    chain: INPUT
    protocol: tcp
    destination_port: 80
    ctstate: NEW
    jump: ACCEPT
    comment: Allow Certbot communication

- name: Open udp 80
  ansible.builtin.iptables:
    action: insert
    chain: INPUT
    protocol: udp
    destination_port: 80
    ctstate: NEW
    jump: ACCEPT
    comment: Allow Certbot UDP communication

- name: Save iptables
  ansible.builtin.shell:
    cmd: iptables-save | grep -v f2b- > /etc/iptables/rules.v4
