---
- name: Nginx http auth jail
  ansible.builtin.copy:
    src: nginx_http_auth.conf
    dest: /etc/fail2ban/jail.d/nginx_http_auth.conf
    owner: "root"
    group: "root"
    mode: "0644"
  register: fail2ban_conf

- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    enabled: True
    state: restarted
  when: fail2ban_conf.changed
